In [ ]:
# https://docs.pytorch.org/tutorials/beginner/introyt/introyt1_tutorial.html
# https://docs.pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html

## Learnings

- Broadcasting Rules: Used for batch operations in deep learning, example: multiplying a batch (4,3,2) by (3,2)
  - No empty tensors!
  - Go Right to left
    - Number matches exactly, or
    - Either number is one, or
    - Either number is missing
- In-place ops
  - Rather than doing `a = torch.clamp(a, -0.5, 0.5)`, you can do:
    - `torch.clamp_(a, -0.5, 0.5)`
    - clamp just clamps all values greater or lower to the value specified and doesnt change any values within that range. Like Relu
- Cloning
  - You can clone a tensor and it's `requires_grad` settings using `a.clone()`
  - If you don't want gradients tracked, you can use `a.detach().clone()`
  - When you do a = b, then id doesn't allocate new memory, `id(a) = id(b)`
  - But when you do `a = b.clone()`, then `id(a) != id(b)`
- Changing Dims
  - unsqueeze and squeeze only work on dims of 1
  - the input they take is which dim, for example 0 will sq/unsq dim 0, 1 will sq/unsq dim 1, and so on....
  - they can be used to make broadcasting work. For example if you wanna multiply a vector of shape `(4,3,2)` with a vector of shape `(3)`, then broadcasting is illegal, however if you unsqueeze the second vector at dim 1 using b.unsqueeze(1), then the new vector becomes `(3, 1)` and multiplication will work
  - reshaping changes the shape but any change to og vector will get propagated to new vector. If you dont want this, use `.clone()`

In [ ]:
# Intro

In [ ]:
import torch

In [ ]:
torch.manual_seed(42)
torch.rand(2, 2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [ ]:
torch.ones(3,3)-1

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.svd(torch.rand(3,3))

torch.return_types.svd(
U=tensor([[-0.3834,  0.2098,  0.8994],
        [-0.6064,  0.6773, -0.4165],
        [-0.6966, -0.7051, -0.1324]]),
S=tensor([1.9324, 0.5834, 0.1384]),
V=tensor([[-0.6634, -0.0677, -0.7452],
        [-0.6284,  0.5910,  0.5058],
        [-0.4061, -0.8039,  0.4346]]))

In [ ]:
# Tensors

In [ ]:
torch.empty(3,3)

tensor([[4.3569e-16, 0.0000e+00, 9.1477e-41],
        [0.0000e+00, 4.2039e-45, 0.0000e+00],
        [3.5873e-43, 0.0000e+00, 1.6042e-27]])

In [ ]:
x = torch.rand((3,3))
x

tensor([[0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])

In [ ]:
torch.randn_like(x)

tensor([[-1.3627,  1.3564,  0.6688],
        [-0.7077, -0.3267, -0.2788],
        [-0.4220, -1.3323, -0.3639]])

In [ ]:
# Broadcasting

In [ ]:
ones = torch.ones(2,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
twos = torch.ones(1,4) * 2
twos

tensor([[2., 2., 2., 2.]])

In [ ]:
ones * twos

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [ ]:
ones.shape, twos.shape

(torch.Size([2, 4]), torch.Size([1, 4]))

In [ ]:
threes = torch.ones(4) * 3

In [ ]:
threes

tensor([3., 3., 3., 3.])

In [ ]:
ones.shape, threes.shape

(torch.Size([2, 4]), torch.Size([4]))

In [ ]:
ones * threes

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [ ]:
a = torch.ones(4, 3, 2)

In [ ]:
b = torch.rand(3, 2) * 2
c = torch.rand(3, 1) * 2
d = torch.rand(1, 2) * 2

In [ ]:
a.shape, b.shape

(torch.Size([4, 3, 2]), torch.Size([3, 2]))

In [ ]:
a

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
b

tensor([[1.4209, 1.8928],
        [1.5781, 0.5628],
        [1.5773, 1.1789]])

In [ ]:
a * b

tensor([[[1.4209, 1.8928],
         [1.5781, 0.5628],
         [1.5773, 1.1789]],

        [[1.4209, 1.8928],
         [1.5781, 0.5628],
         [1.5773, 1.1789]],

        [[1.4209, 1.8928],
         [1.5781, 0.5628],
         [1.5773, 1.1789]],

        [[1.4209, 1.8928],
         [1.5781, 0.5628],
         [1.5773, 1.1789]]])

In [ ]:
a.shape, c.shape

(torch.Size([4, 3, 2]), torch.Size([3, 1]))

In [ ]:
a

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
c

tensor([[1.5078],
        [0.3905],
        [0.0101]])

In [ ]:
a * c

tensor([[[1.5078, 1.5078],
         [0.3905, 0.3905],
         [0.0101, 0.0101]],

        [[1.5078, 1.5078],
         [0.3905, 0.3905],
         [0.0101, 0.0101]],

        [[1.5078, 1.5078],
         [0.3905, 0.3905],
         [0.0101, 0.0101]],

        [[1.5078, 1.5078],
         [0.3905, 0.3905],
         [0.0101, 0.0101]]])

In [ ]:
a.shape, d.shape

(torch.Size([4, 3, 2]), torch.Size([1, 2]))

In [ ]:
a

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
d

tensor([[0.6136, 0.2330]])

In [ ]:
a * d

tensor([[[0.6136, 0.2330],
         [0.6136, 0.2330],
         [0.6136, 0.2330]],

        [[0.6136, 0.2330],
         [0.6136, 0.2330],
         [0.6136, 0.2330]],

        [[0.6136, 0.2330],
         [0.6136, 0.2330],
         [0.6136, 0.2330]],

        [[0.6136, 0.2330],
         [0.6136, 0.2330],
         [0.6136, 0.2330]]])

In [ ]:
# More Math

In [ ]:
a = torch.rand(2, 4) * 2 - 1

In [ ]:
a

tensor([[ 0.8205,  0.2880,  0.4142,  0.3163],
        [-0.0174,  0.7826, -0.7105,  0.0630]])

In [ ]:
torch.clamp(a, -0.5, 0.5)

tensor([[ 0.5000,  0.2880,  0.4142,  0.3163],
        [-0.0174,  0.5000, -0.5000,  0.0630]])

In [ ]:
d = torch.tensor([[1., 1.], [3., 4.]])

In [ ]:
e = torch.ones(1, 2)

In [ ]:
d

tensor([[1., 1.],
        [3., 4.]])

In [ ]:
e

tensor([[1., 1.]])

In [ ]:
torch.eq(d, e)

tensor([[ True,  True],
        [False, False]])

In [ ]:
a = torch.tensor([1,2,3,4])

In [ ]:
a

tensor([1, 2, 3, 4])

In [ ]:
torch.clamp_(a, 1, 2)

tensor([1, 2, 2, 2])

In [ ]:
a

tensor([1, 2, 2, 2])

In [ ]:
# Altering tensors in-place

In [ ]:
import torch

In [ ]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)

In [ ]:
old_id = id(c)

In [ ]:
old_id

135015488651424

In [ ]:
print(c)

tensor([[0., 0.],
        [0., 0.]])


In [ ]:
d = torch.matmul(a, b, out=c)

In [ ]:
d

tensor([[0.7828, 0.7568],
        [0.8603, 0.9742]])

In [ ]:
c

tensor([[0.7828, 0.7568],
        [0.8603, 0.9742]])

In [ ]:
id(c)

135015488651424

In [ ]:
id(d)

135015488651424

In [ ]:
# Clone

In [ ]:
a = torch.ones(2,2)
b = a.clone()

In [ ]:
c = a

In [ ]:
id(a), id(b), id(c)

(135011180080224, 135015488652704, 135011180080224)

In [ ]:
a = torch.rand(2, 2, requires_grad=True)
b = a.clone()
c = a.detach().clone()

In [ ]:
id(a), id(b), id(c)

(135011177103296, 135011186439856, 135011179072160)

In [ ]:
print(a)
print(b)
print(c)

tensor([[0.7545, 0.9425],
        [0.3151, 0.0315]], requires_grad=True)
tensor([[0.7545, 0.9425],
        [0.3151, 0.0315]], grad_fn=<CloneBackward0>)
tensor([[0.7545, 0.9425],
        [0.3151, 0.0315]])


In [ ]:
torch.accelerator.current_accelerator()

device(type='cuda')

In [ ]:
# (Imp) Manipulating Tensor Shapes

In [ ]:
a = torch.rand(3, 226, 226)

In [ ]:
a.unsqueeze(0).shape

torch.Size([1, 3, 226, 226])

In [ ]:
c = torch.rand(1, 1, 1, 1, 2)

In [ ]:
a = torch.rand(1, 20)

In [ ]:
a.shape

torch.Size([1, 20])

In [ ]:
id(a)

135011177622224

In [ ]:
a.squeeze_(0)

tensor([0.7517, 0.1361, 0.9488, 0.5507, 0.5622, 0.9372, 0.4454, 0.3179, 0.3189,
        0.0435, 0.0402, 0.2557, 0.3086, 0.6764, 0.3523, 0.1249, 0.9766, 0.9247,
        0.7761, 0.7323])

In [ ]:
id(a)

135011177622224

In [ ]:
c = torch.rand(2, 2)
c.shape

torch.Size([2, 2])

In [ ]:
c.squeeze(0).shape

torch.Size([2, 2])

In [ ]:
a = torch.ones(4, 3, 2)

In [ ]:
a.shape

torch.Size([4, 3, 2])

In [ ]:
c = a * torch.rand(3, 1)
c.shape

torch.Size([4, 3, 2])

In [ ]:
a.shape

torch.Size([4, 3, 2])

In [ ]:
b = torch.rand(3)

In [ ]:
a.shape, b.shape

(torch.Size([4, 3, 2]), torch.Size([3]))

In [ ]:
a * b

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [ ]:
b.unsqueeze(0).shape

torch.Size([1, 3])

In [ ]:
b.unsqueeze(1).shape

torch.Size([3, 1])

In [ ]:
c = a * b.unsqueeze(1)

In [ ]:
c.shape

torch.Size([4, 3, 2])

In [ ]:
output3d = torch.rand(6, 20, 20)

In [ ]:
output3d.shape

torch.Size([6, 20, 20])

In [ ]:
output3d.reshape(1, 6*20*20).shape

torch.Size([1, 2400])

In [ ]:
a = torch.ones(1, 3)

In [ ]:
b = a.squeeze(0)

In [ ]:
b.shape

torch.Size([3])

In [ ]:
b

tensor([1., 1., 1.])

In [ ]:
a

tensor([[1., 1., 1.]])

In [ ]:
a = torch.rand(6, 20, 20)
b = a.reshape(6*20*20)

In [ ]:
a.shape, b.shape

(torch.Size([6, 20, 20]), torch.Size([2400]))

In [ ]:
id(a), id(b)

(135011163989616, 135011163982496)

In [ ]:
a[0][0][0] = 1

In [ ]:
id(a), id(b)

(135011163989616, 135011163982496)