In [ ]:
# https://docs.pytorch.org/tutorials/beginner/introyt/modelsyt_tutorial.html

## Learnings
- View
  - Reshapes the tensor given new shape
  - Infers at position where -1 is given
  - Tensor needs to be contiguous in memory
- Dropout
  - Randomly sets p% of your tensor of say size (1, 4, 4) to 0 during tra

In [ ]:
import torch

In [ ]:
# Linear Layers

In [ ]:
class TinyModel(torch.nn.Module):
  def __init__(self):
    super(TinyModel, self).__init__()

    self.linear1 = torch.nn.Linear(100, 200)
    self.activation = torch.nn.ReLU()
    self.linear2 = torch.nn.Linear(200, 10)
    self.softmax = torch.nn.Softmax()

  def forward(self, x):
    x = self.linear1(x)
    x = self.activation(x)
    x = self.linear2(x)
    x = self.softmax(x)

In [ ]:
tinymodel = TinyModel()

In [ ]:
tinymodel.linear1.weight.shape

torch.Size([200, 100])

In [ ]:
tinymodel.linear2.weight.shape

torch.Size([10, 200])

In [ ]:
for param in tinymodel.linear1.parameters():
  print(param.shape)

torch.Size([200, 100])
torch.Size([200])


In [ ]:
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)

In [ ]:
y = lin(x)

In [ ]:
y.shape

torch.Size([1, 2])

In [ ]:
for param in lin.parameters():


Parameter containing:
tensor([[-0.4469,  0.4911,  0.0507],
        [-0.2235, -0.3439,  0.4944]], requires_grad=True)
Parameter containing:
tensor([ 0.0691, -0.5620], requires_grad=True)


In [ ]:
w = torch.tensor([[-0.4469,  0.4911,  0.0507],
        [-0.2235, -0.3439,  0.4944]], requires_grad=True)

In [ ]:
b =  torch.tensor([ 0.0691, -0.5620], requires_grad=True)

In [ ]:
y

tensor([[ 0.1324, -0.7108]], grad_fn=<AddmmBackward0>)

In [ ]:
x.shape, w.shape, b.shape

(torch.Size([1, 3]), torch.Size([2, 3]), torch.Size([2]))

In [ ]:
y_dash = x @ w.T + b

In [ ]:
y_dash

tensor([[ 0.1324, -0.7108]], grad_fn=<AddBackward0>)

In [ ]:
# Conv Layers

In [ ]:
# ...skip

In [ ]:
# Recurrent Layers

In [ ]:
# ... skip

In [ ]:
# Transformer layers

In [ ]:
# ... skip

In [ ]:
# DropOut and BatchNorm layers

In [ ]:
my_tensor = torch.rand(2, 4, 4) * 20 + 5

In [ ]:
my_tensor

tensor([[[18.9978, 14.6357, 18.9201,  7.8985],
         [20.4196, 21.0068, 17.5986, 22.8354],
         [ 7.4894, 17.0048, 24.6220, 22.1810],
         [21.1089, 16.1011, 21.0737, 24.3929]],

        [[15.5507, 22.2506,  6.7264, 22.3605],
         [15.2730,  6.2225, 23.9892, 11.6445],
         [ 9.2229, 18.1476, 16.6241,  5.0528],
         [11.4305,  6.2980, 19.7381, 22.2359]]])

In [ ]:
my_tensor.mean()

tensor(16.5329)

In [ ]:
norm_layer = torch.nn.BatchNorm1d(4)

In [ ]:
normed_tensor = norm_layer(my_tensor)

In [ ]:
normed_tensor

tensor([[[ 0.5503, -0.2290,  0.5364, -1.4325],
         [ 0.5367,  0.6401,  0.0396,  0.9623],
         [-1.1429,  0.2968,  1.4494,  1.0800],
         [ 0.5761, -0.2951,  0.5700,  1.1474]],

        [[-0.0655,  1.1313, -1.6419,  1.1510],
         [-0.3701, -1.9647,  1.1656, -1.0094],
         [-0.8807,  0.4697,  0.2392, -1.5116],
         [-1.1077, -2.0006,  0.3376,  0.7722]]],
       grad_fn=<NativeBatchNormBackward0>)

In [ ]:
print(normed_tensor.mean())

tensor(1.4901e-08, grad_fn=<MeanBackward0>)


In [ ]:
my_tensor = torch.rand(1, 4, 4)

In [ ]:
dropout = torch.nn.Dropout(0.4)

In [ ]:
dropout(my_tensor)

tensor([[[0.3086, 0.0000, 0.0000, 0.9171],
         [1.3632, 0.8882, 0.0000, 0.0000],
         [0.8483, 0.0000, 1.0971, 1.5373],
         [0.0000, 0.7967, 0.0000, 0.0000]]])

In [ ]:
# View

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor.shape

torch.Size([2, 3])

In [ ]:
tensor_view = tensor.view(6)

In [ ]:
id(tensor), id(tensor_view)

(134152549764304, 134156706890128)

In [ ]:
tensor.shape

torch.Size([2, 3])

In [ ]:
tensor.shape

torch.Size([2, 3])

In [ ]:
tensor = torch.randn(2, 3, 4)

In [ ]:
tensor.shape

torch.Size([2, 3, 4])

In [ ]:
tensor.view(2, 6, -1).shape

torch.Size([2, 6, 2])