# Understanding requires_grad, retain_grad, Leaf, and Non-leaf Tensors

Same Learnings as before

In [ ]:
# https://docs.pytorch.org/tutorials/beginner/understanding_leaf_vs_nonleaf_tutorial.html

In [ ]:
import torch
import torch.nn.functional as F

In [ ]:
x = torch.ones(1, 3)
y = torch.ones(1, 2)

In [ ]:
W = torch.ones(3, 2, requires_grad=True)
b = torch.ones(2, requires_grad=True)

In [ ]:
z = x @ W + b
y_pred = F.relu(z)
loss = F.mse_loss(y_pred, y)

In [ ]:
loss

tensor(9., grad_fn=<MseLossBackward0>)

# A guide on good usage of non_blocking and pin_memory() in PyTorch

## Learnings
-  Together, the available space in disk and RAM (physical memory) make up the virtual memory
-  In short, the virtual memory makes it so that the available space is larger than what can be found on RAM in isolation and creates the illusion that the main memory is larger than it actually is.
-  a regular CPU tensor is pageable which means that it is divided in blocks called pages that can live anywhere in the virtual memory (both in RAM or on disk)
- when a program accesses a page that is not in RAM, a “page fault” occurs and the operating system (O?S) then brings back this page into RAM
- In turn, the OS may have to swap out (or “page out”) another page to make room for the new page.
- In contrast to pageable memory, a pinned memory (or page-locked or non-pageable) is a type of memory that cannot be swapped out to disk.
- CUDA and (non-)pageable memory
  - If the memory is page-locked, the device can access the memory directly in the main memory. data can be significantly accelerated.
  - If the memory is pageable, all the pages will have to be brought to the main memory before being sent to the GPU. This operation may take time and is less predictable than when executed on page-locked tensors.


In [ ]:
# https://docs.pytorch.org/tutorials/intermediate/pinmem_nonblock.html

# Visualizing Gradients

## Learnings
-

In [ ]:
# https://docs.pytorch.org/tutorials/intermediate/visualizing_gradients_tutorial.html

In [ ]:
import torch

In [ ]:
x = torch.tensor([[5., 3.], [1., 2.], [4., 6.]])
torch.nn.BatchNorm1d(2)(x)

tensor([[ 0.9806, -0.3922],
        [-1.3728, -0.9806],
        [ 0.3922,  1.3728]], grad_fn=<NativeBatchNormBackward0>)

In [ ]:
x

tensor([[5., 3.],
        [1., 2.]])

In [ ]:
class BatchNorm(torch.nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self, x):
    x_mean = x.mean(0)
    x_std = (x - x.mean(0)).pow(2).mean(0).sqrt()
    return (x - x_mean)/x_std


In [ ]:
model = BatchNorm()

In [ ]:
model(x)

tensor([[ 0.9806, -0.3922],
        [-1.3728, -0.9806],
        [ 0.3922,  1.3728]])